### ISSUE TITLE
Magento 2.2 compatibility

### ISSUE THREAD

**Issue by Hocdoc** [Agence-DnD/PIMGento-2#148]
Can I use PIMGento-2 with the new Magento 2.2 release?
Any experiences?

**Comment by juzo-ec** [comment]
We are also planning on updating soon. Is it compatible?

**Comment by nocturnalfrog** [comment]
Version 100.2.22 is NOT compatible with Magento 2.2:

```
1 exception(s):
Exception #0 (InvalidArgumentException): Unable to unserialize value.

Exception #0 (InvalidArgumentException): Unable to unserialize value.
#0 /data/web/magento2/vendor/magento/module-config/Model/Config/Backend/Serialized.php(55): Magento\Framework\Serialize\Serializer\Json->unserialize('a:1:{s:18:"_150...')
#1 /data/web/magento2/vendor/magento/framework/Model/AbstractModel.php(601): Magento\Config\Model\Config\Backend\Serialized->_afterLoad()
#2 /data/web/magento2/generated/code/Magento/Config/Model/Config/Backend/Serialized/ArraySerialized/Interceptor.php(323): Magento\Framework\Model\AbstractModel->afterLoad()
#3 /data/web/magento2/vendor/magento/module-config/Block/System/Config/Form.php(438): Magento\Config\Model\Config\Backend\Serialized\ArraySerialized\Interceptor->afterLoad()
#4 /data/web/magento2/vendor/magento/module-config/Block/System/Config/Form.php(348): Magento\Config\Block\System\Config\Form->getFieldData(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), 'pimgento/genera...')
#5 /data/web/magento2/vendor/magento/module-config/Block/System/Config/Form.php(324): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'pimgento/genera...', '', '')
#6 /data/web/magento2/vendor/magento/module-config/Block/System/Config/Form.php(264): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section))
#7 /data/web/magento2/vendor/magento/module-config/Block/System/Config/Form.php(210): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#8 /data/web/magento2/vendor/magento/module-config/Block/System/Config/Form.php(549): Magento\Config\Block\System\Config\Form->initForm()
#9 /data/web/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#10 /data/web/magento2/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 /data/web/magento2/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#12 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#13 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#14 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#15 /data/web/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#16 /data/web/magento2/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#17 /data/web/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/data/web/magen...')
#18 /data/web/magento2/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/data/web/magen...', Array)
#19 /data/web/magento2/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/data/web/magen...')
#20 /data/web/magento2/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#21 /data/web/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#22 /data/web/magento2/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 /data/web/magento2/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#24 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#25 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#26 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#27 /data/web/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#28 /data/web/magento2/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#29 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#30 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#31 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#32 /data/web/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#33 /data/web/magento2/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#34 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#35 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#36 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#37 /data/web/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#38 /data/web/magento2/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#39 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#40 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#41 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#42 /data/web/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#43 /data/web/magento2/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#44 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#45 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#46 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#47 /data/web/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#48 /data/web/magento2/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#49 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#50 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#51 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#52 /data/web/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#53 /data/web/magento2/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#54 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#55 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#56 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#57 /data/web/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#58 /data/web/magento2/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#59 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#60 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#61 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#62 /data/web/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#63 /data/web/magento2/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#64 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#65 /data/web/magento2/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#66 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#67 /data/web/magento2/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#68 /data/web/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#69 /data/web/magento2/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#70 /data/web/magento2/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /data/web/magento2/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /data/web/magento2/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#73 /data/web/magento2/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#74 /data/web/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#75 {main}
```

**Comment by nocturnalfrog** [comment]
https://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes.html#database-data-format-changes

**Comment by Silarn** [comment]
This is twofold. You need to change the unserialize functions called on the core_config_data data to the new JsonSerializer class and also update any existing serialized data to the new JSON format.

**Comment by hostep** [comment]
Magento should already convert the serialized values stored in the `core_config_data` table automatically I believe.

But you don't have to forget to change the default values defined in the `config.xml` files, for example:
https://github.com/Agence-DnD/PIMGento-2/blob/dab6fd9/Product/etc/config.xml#L6-L7

And even if the default value of a serialized config field should be empty, you now need to define it in the `config.xml` file as `<my_config>{}</my_config>`, otherwise you'll run into problems.

Just FYI :)

**Comment by spipu** [comment]
On an existing project that has already savec valus in database, you have to vreate a dataUpgrade setup to convert the values ton json format.

The magento 2.2 upgrade guide guices an gowto example.

**Comment by nocturnalfrog** [comment]
Look like there's a PR available that fixes the compatibility issues: https://github.com/Agence-DnD/PIMGento-2/pull/161
