### ISSUE TITLE
MySQL has gone away when importing product

### ISSUE THREAD

**Issue by renaud-fasimana-te** [Agence-DnD/PIMGento-2#174]
Hello,

I am facing an issue when importing a product.
Im using Magento EE 2.2.1, Akeneo 2.0.9
I have 540 categories, 65 family, 466 attributes and 2222 options so far in pimgento_entities.
Import product stops at "updateOption" step

> Exception: Warning: PDOStatement::execute(): MySQL server has gone away in /var/www/magento/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228 in /var/www/magento/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'PDOStatement::e...', '/home/magento/w...', 228, Array)
#1 /var/www/magento/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#2 /var/www/magento/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#3 /var/www/magento/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#4 /var/www/magento/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#5 /var/www/magento/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `tm...', Array)
#6 /var/www/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `tm...', Array)
#7 /var/www/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `tm...', Array)
#8 /var/www/magento/vendor/agencednd/module-pimgento/Product/Model/Factory/Import.php(504): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `tm...')
#9 /var/www/magento/vendor/agencednd/module-pimgento/Import/Model/Factory.php(79): Pimgento\Product\Model\Factory\Import->updateOption()
#10 /var/www/magento/vendor/agencednd/module-pimgento/Import/Console/Command/PimgentoImportCommand.php(91): Pimgento\Import\Model\Factory->execute()
#11 /var/www/magento/vendor/agencednd/module-pimgento/Import/Console/Command/PimgentoImportCommand.php(73): Pimgento\Import\Console\Command\PimgentoImportCommand->_import('product', 'export_product_...', Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/magento/vendor/symfony/console/Command/Command.php(242): Pimgento\Import\Console\Command\PimgentoImportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/magento/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/magento/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Pimgento\Import\Console\Command\PimgentoImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/magento/vendor/magento/framework/Console/Cli.php(104): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/magento/vendor/symfony/console/Application.php(117): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/magento/bin/magento(23): Symfony\Component\Console\Application->run()
#18 {main}

Any idea? LEt me know if you need more information.

Thanks

**Comment by akosglue** [comment]
May be related:
https://github.com/Agence-DnD/PIMGento-2/issues/169
https://github.com/Agence-DnD/PIMGento-2/issues/144
