### ISSUE TITLE
Product data imports not correctly inserting into Magento 

### ISSUE THREAD

**Issue by olliem** [Agence-DnD/PIMGento-2#187]
Hi,

I'm having a frustrating time trying to get imports working. All the imports appear to run successfully. However, data isn't seemingly making its way into the database and it's causing Magento to crash when editing a product. I have a feeling its due to the attributes not having been inserted by the plugin into the Magento database correctly.

![image](https://user-images.githubusercontent.com/10209/39618519-08d97eda-4f7c-11e8-8eb0-32689404a101.png)

**Our imported product file**
![image](https://user-images.githubusercontent.com/10209/39618527-10d352aa-4f7c-11e8-864a-ab14e9091035.png)

**Products are created but no titles**
![image](https://user-images.githubusercontent.com/10209/39618535-1a02ebec-4f7c-11e8-963d-cd966f1e625a.png)

**Magento 2.2 stacktrace when editing product**
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "formElement" is a required for "title" field.

Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "formElement" is a required for "title" field.
#0 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(159): Magento\Ui\Component\Form\Field->prepare()
#1 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Field))
#2 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Container))
#3 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Fieldset))
#4 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(137): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form))
#5 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(97): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#6 /var/www/html/vendor/magento/framework/View/Layout/GeneratorPool.php(80)

Has anyone come across this before or have any ideas how to resolve this?

**Comment by dnd-derwent** [comment]
Hi @olliem 

I tried to reproduce your issue, but could not come across the exception.
The display of the title in the product grid depends on the locale configured on the default config (store_id = 0).
Pimgento will take the value from this locale to set it to the product with store_id = 0.
In your case, if the locale is not en_GB, it will be filled with empty values (coming from other locales).
Can you try to set the locale to en_GB for the default config and re-import your product file to update the values ?

**Comment by Layer5-PaulC** [comment]
Hi there, I have found the main crux of the issue - or rather I *think* I have

There was legacy (broken) data in the PimGento attributes import table, so I cleared them all out at database level and re-imported from the top - including the Attribute Sets / Families definition.

At that point I got nice new Attributes defined (which increased ID numbers - previously they were adopting the same ID as before - which was my clue as to why the legacy data was persisting) and they have a back-end model

So the take away here, is repeatedly importing the file didn't seem to give me a full "start again" process on attributes - the bad data was remembered.

**Comment by bartoszkubicki** [comment]
I had the same issue, and I am sure that is because of broken data in akeneo. But despite of that fact, pimgento should validate that before inserting it into db.
https://github.com/Agence-DnD/PIMGento-2/issues/217
